server:
  port: 8004
  servlet:
    context-path: /imooc-study-ecommerce-dev

spring:
  # SpringBoot 集成 Kafka 的配置, 最低配置只需要配置 spring.kafka.bootstrap-servers
  kafka:
    bootstrap-servers: 192.168.218.129:9092
      #    consumer:
      # 如果 Consumer 没有指定 group-id, 则使用配置文件中配置的; 如果配置文件中也没有定义, 则由框架随机生成
#      group-id: imooc-study-ecommerce
#      auto-offset-reset: latest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# RocketMQ 的配置, 这是最低配置
rocketmq:
  name-server: 192.168.218.129:9876
  producer:
    # 发送同一类消息的设置为同一个 group, 保证唯一
    group: imooc-study-ecommerce