server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&allowMultiQueries=true
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  ## redis配置
  redis:
    database: 0 # 数据库索引 默认为0
    host: 127.0.0.1    # redis服务器地址
    port: 7000    # 端口号
    password:    # 密码（默认为空）
    timeout: 5000 # 连接超时时间（毫秒）
    jedis:
      pool: # 连接池配置
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
mybatis:
  mapper-locations: classpath:mapper/*.xml

